from django.core.exceptions import ValidationError
import re

def validate_dialogue_text(dialogue_text):
    pass