from django.core.exceptions import ValidationError
import re

def validate_char_type(char_type):
    pass